# fly.toml app configuration file generated for recipe-finder99 on 2023-12-03T19:51:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "recipe-finder99"
primary_region = "otp"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
